# Generated by Django 3.0.2 on 2020-07-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200214_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='anthem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
