# Generated by Django 3.0.2 on 2020-07-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200722_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
